server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple-instances
          uri: https://github.com/sornerito/microservicios-eureka
          search-paths: config-data
  application:
    name: config-service